import { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  buildInsertRowPayload,
  canUseDefaultMode,
  canUseNullMode,
  createInitialFieldStates,
  formatDefaultHint,
  type InsertRowFieldMode,
  type InsertRowFieldState,
  type InsertRowValidationCode,
  isInsertInputHidden,
  requiresInsertValue,
  validateInsertRowFields,
} from '@/features/table-view/lib/insertRowForm';
import { Modal } from '@/shared/components/Modal';
import { api } from '@/shared/lib/api';
import { formatError } from '@/shared/lib/normalize';
import type { ColumnInfo, DriverType } from '@/types';

interface Props {
  connectionId: string;
  driver: DriverType;
  schema: string;
  table: string;
  onClose: () => void;
  onConfirm: (values: Record<string, unknown>) => Promise<void>;
}

function FieldModePicker({
  col,
  driver,
  state,
  saving,
  onModeChange,
  onValueChange,
}: {
  col: ColumnInfo;
  driver: DriverType;
  state: InsertRowFieldState;
  saving: boolean;
  onModeChange: (mode: InsertRowFieldMode) => void;
  onValueChange: (value: string) => void;
}) {
  const { t } = useTranslation();
  const hidden = isInsertInputHidden(col, driver);
  const showDefault = canUseDefaultMode(col, driver);
  const showNull = canUseNullMode(col);
  const showModePicker = !hidden && (showDefault || showNull);
  const defaultHint = formatDefaultHint(col, driver);
  const inputEnabled = !saving && !hidden && state.mode === 'value';

  const inputPlaceholder =
    state.mode === 'default'
      ? defaultHint || t('tableView.addRowDialog.inputPlaceholderDefault')
      : state.mode === 'null'
        ? t('tableView.addRowDialog.inputPlaceholderNull')
        : t('tableView.addRowDialog.inputPlaceholderValue');

  if (hidden) {
    return (
      <div className="table-view-add-row-field-body table-view-add-row-field-managed">
        <p className="table-view-add-row-context-hint table-view-add-row-context-hint-muted">
          {t('tableView.addRowDialog.autoGenerated')}
          {defaultHint ? (
            <>
              {' '}
              <code className="table-view-add-row-default-expr">{defaultHint}</code>
            </>
          ) : null}
        </p>
      </div>
    );
  }

  return (
    <div className="table-view-add-row-field-body">
      {showModePicker && (
        <div
          className="table-view-add-row-mode"
          role="radiogroup"
          aria-label={t('tableView.addRowDialog.modeGroup', { column: col.name })}
        >
          {showDefault && (
            <button
              type="button"
              role="radio"
              aria-checked={state.mode === 'default'}
              className={`table-view-add-row-mode-btn${state.mode === 'default' ? ' active' : ''}`}
              disabled={saving}
              onClick={() => onModeChange('default')}
            >
              {t('tableView.addRowDialog.modeDefault')}
            </button>
          )}
          {showNull && (
            <button
              type="button"
              role="radio"
              aria-checked={state.mode === 'null'}
              className={`table-view-add-row-mode-btn${state.mode === 'null' ? ' active' : ''}`}
              disabled={saving}
              onClick={() => onModeChange('null')}
            >
              {t('common.null')}
            </button>
          )}
          <button
            type="button"
            role="radio"
            aria-checked={state.mode === 'value'}
            className={`table-view-add-row-mode-btn${state.mode === 'value' ? ' active' : ''}`}
            disabled={saving}
            onClick={() => onModeChange('value')}
          >
            {t('tableView.addRowDialog.modeValue')}
          </button>
        </div>
      )}

      {state.mode === 'default' && defaultHint && (
        <p className="table-view-add-row-context-hint">
          <span className="table-view-add-row-default-label">{t('tableView.addRowDialog.defaultExpression')}</span>
          <code className="table-view-add-row-default-expr">{defaultHint}</code>
        </p>
      )}
      {state.mode === 'default' && !defaultHint && col.isNullable && (
        <p className="table-view-add-row-context-hint table-view-add-row-context-hint-muted">
          {t('tableView.addRowDialog.defaultOmitNullable')}
        </p>
      )}
      {state.mode === 'null' && (
        <p className="table-view-add-row-context-hint table-view-add-row-context-hint-muted">
          {t('tableView.addRowDialog.nullHint')}
        </p>
      )}
      <input
        id={`add-row-${col.name}`}
        className="table-view-add-row-input"
        value={state.mode === 'value' ? state.value : ''}
        disabled={!inputEnabled}
        placeholder={inputPlaceholder}
        aria-label={col.name}
        onChange={(e) => onValueChange(e.target.value)}
      />
    </div>
  );
}

export function TableViewAddRowDialog({ connectionId, driver, schema, table, onClose, onConfirm }: Props) {
  const { t } = useTranslation();

  const [columns, setColumns] = useState<ColumnInfo[]>([]);
  const [fields, setFields] = useState<Record<string, InsertRowFieldState>>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [loadError, setLoadError] = useState('');
  const [submitError, setSubmitError] = useState('');
  const [validationCode, setValidationCode] = useState<InsertRowValidationCode>(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setLoadError('');
    void api
      .listColumns(connectionId, schema, table)
      .then((cols) => {
        if (cancelled) return;
        setColumns(cols);
        setFields(createInitialFieldStates(cols, driver));
      })
      .catch((e) => {
        if (!cancelled) setLoadError(formatError(e));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [connectionId, driver, schema, table]);

  const validationMessage = (code: InsertRowValidationCode): string => {
    switch (code) {
      case 'required':
        return t('tableView.addRowDialog.errorRequired');
      case 'notNullable':
        return t('tableView.addRowDialog.errorNotNullable');
      case 'emptyInsert':
        return t('tableView.addRowDialog.errorEmpty');
      default:
        return '';
    }
  };

  const updateField = useCallback((name: string, patch: Partial<InsertRowFieldState>) => {
    setFields((prev) => ({
      ...prev,
      [name]: { ...prev[name], ...patch },
    }));
    setValidationCode(null);
  }, []);

  const setFieldMode = useCallback((name: string, mode: InsertRowFieldMode, value?: string) => {
    setFields((prev) => {
      const cur = prev[name];
      if (!cur) return prev;
      return {
        ...prev,
        [name]: {
          mode,
          value: mode === 'value' ? (value ?? cur.value) : '',
        },
      };
    });
    setValidationCode(null);
  }, []);

  const submit = async () => {
    const code = validateInsertRowFields(columns, fields, driver);
    if (code) {
      setValidationCode(code);
      return;
    }
    const values = buildInsertRowPayload(columns, fields, driver);
    setSaving(true);
    setValidationCode(null);
    setSubmitError('');
    try {
      await onConfirm(values);
    } catch (e) {
      setSubmitError(formatError(e));
    } finally {
      setSaving(false);
    }
  };

  return (
    <Modal title={t('tableView.addRowDialog.title', { table })} onClose={onClose} size="md" scrollBody>
      <div className="modal-body">
        {loading ? (
          <p className="table-view-add-row-status">{t('tableView.addRowDialog.loading')}</p>
        ) : loadError && columns.length === 0 ? (
          <p className="form-alert form-alert--error">{loadError}</p>
        ) : (
          <>
            <p className="modal-description">{t('tableView.addRowDialog.description')}</p>
            {submitError && <p className="form-alert form-alert--error">{submitError}</p>}
            {validationCode && <p className="form-alert form-alert--error">{validationMessage(validationCode)}</p>}
            <div className="table-view-add-row-fields">
              {columns.map((col) => {
                const state = fields[col.name];
                if (!state) return null;

                return (
                  <div key={col.name} className="table-view-add-row-field">
                    <div className="table-view-add-row-field-head">
                      <span className="table-view-add-row-label">
                        {col.name}
                        <span className="table-view-add-row-type">{col.dataType}</span>
                      </span>
                      <div className="table-view-add-row-badges">
                        {col.isPrimary && (
                          <span className="table-view-add-row-badge">
                            {t('tableView.addRowDialog.primaryKeyBadge')}
                          </span>
                        )}
                        {col.isForeign && (
                          <span className="table-view-add-row-badge">
                            {t('tableView.addRowDialog.foreignKeyBadge')}
                          </span>
                        )}
                        {requiresInsertValue(col, driver) && (
                          <span className="table-view-add-row-badge table-view-add-row-badge-required">
                            {t('tableView.addRowDialog.requiredBadge')}
                          </span>
                        )}
                      </div>
                    </div>
                    <FieldModePicker
                      col={col}
                      driver={driver}
                      state={state}
                      saving={saving}
                      onModeChange={(mode) => setFieldMode(col.name, mode)}
                      onValueChange={(value) => updateField(col.name, { mode: 'value', value })}
                    />
                  </div>
                );
              })}
            </div>
          </>
        )}
      </div>
      <div className="modal-footer">
        <button type="button" className="btn" onClick={onClose} disabled={saving}>
          {t('common.cancel')}
        </button>
        <button
          type="button"
          className="btn btn-primary"
          onClick={() => void submit()}
          disabled={loading || saving || columns.length === 0}
        >
          {t('tableView.addRowDialog.submit')}
        </button>
      </div>
    </Modal>
  );
}
