// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeginTransaction pins a dedicated connection to the tab and opens a transaction.
 * Subsequent ExecuteQueryStream calls for tabID will run on that connection until
 * CommitTransaction or RollbackTransaction is called.
 */
export function BeginTransaction(connectionID: string, tabID: string): $CancellablePromise<void> {
    return $Call.ByID(2187422330, connectionID, tabID);
}

export function CancelQuery(connectionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3821899609, connectionID);
}

/**
 * CleanupTabTransaction rolls back any open transaction for the tab. Called when a tab is closed.
 */
export function CleanupTabTransaction(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(386939206, tabID);
}

export function ClearQueryHistory(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(3511871798, connectionID);
}

/**
 * CommitTransaction commits the open transaction on the tab and releases the pinned connection.
 */
export function CommitTransaction(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(1672899332, tabID);
}

export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(1546757449, id);
}

export function CopyToClipboard(text: string): $CancellablePromise<void> {
    return $Call.ByID(2467530889, text);
}

export function DeleteConnection(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(3337158526, id);
}

export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(183030786, id);
}

export function DeleteQueryHistoryEntry(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(3668220758, id);
}

export function DeleteRows(connectionID: string, del: database$0.RowDelete): $CancellablePromise<number> {
    return $Call.ByID(3419106895, connectionID, del);
}

export function DeleteSavedQuery(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2873411343, id);
}

export function DeleteSetting(key: string): $CancellablePromise<void> {
    return $Call.ByID(3413671862, key);
}

export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(3864830715, id);
}

export function EmitOpenSQLite(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(46205330, filePath);
}

export function ExecuteQuery(connectionID: string, sql: string): $CancellablePromise<database$0.QueryResult | null> {
    return $Call.ByID(1940384492, connectionID, sql).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ExecuteQueryStream(connectionID: string, tabID: string, sql: string): $CancellablePromise<void> {
    return $Call.ByID(3110751220, connectionID, tabID, sql);
}

export function ExportResult(result: database$0.QueryResult, format: string): $CancellablePromise<string> {
    return $Call.ByID(1465290314, result, format);
}

export function FormatSQL(sql: string): $CancellablePromise<string> {
    return $Call.ByID(557421198, sql);
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(1631861786).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetConnectionStatus(connectionID: string): $CancellablePromise<database$0.ConnectionStatus> {
    return $Call.ByID(2880332169, connectionID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetDataDir(): $CancellablePromise<string> {
    return $Call.ByID(3031616142);
}

export function GetEditorSession(): $CancellablePromise<storage$0.EditorSession> {
    return $Call.ByID(881302078).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetPendingFile(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(109090272).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetQueryHistory(connectionID: string, limit: number): $CancellablePromise<database$0.HistoryEntry[]> {
    return $Call.ByID(4033942967, connectionID, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetSettings(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(222085978).then(($result: any) => {
        return $$createType5($result);
    });
}

export function InitStores(configDir: string): $CancellablePromise<void> {
    return $Call.ByID(1152712829, configDir);
}

export function InsertRow(connectionID: string, schema: string, table: string, values: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1655633052, connectionID, schema, table, values).then(($result: any) => {
        return $$createType8($result);
    });
}

export function IsConnected(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1544907504, id);
}

export function ListColumns(connectionID: string, schema: string, table: string): $CancellablePromise<database$0.ColumnInfo[]> {
    return $Call.ByID(3118816600, connectionID, schema, table).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListConnections(): $CancellablePromise<database$0.ConnectionConfig[]> {
    return $Call.ByID(1654481338).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListFolders(): $CancellablePromise<storage$0.ConnectionFolder[]> {
    return $Call.ByID(1373072582).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ListSavedQueries(connectionID: string): $CancellablePromise<database$0.SavedQuery[]> {
    return $Call.ByID(2254370512, connectionID).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ListSchemas(connectionID: string): $CancellablePromise<database$0.SchemaInfo[]> {
    return $Call.ByID(2969331507, connectionID).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ListTables(connectionID: string, schema: string): $CancellablePromise<database$0.TableInfo[]> {
    return $Call.ByID(773846824, connectionID, schema).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * LoadSchemaData preloads tables for the default browse schema; Postgres also preloads "public"
 * so the schema browser is populated even when the default is a custom schema.
 */
export function LoadSchemaData(connectionID: string): $CancellablePromise<database$0.SchemaBundle> {
    return $Call.ByID(4233994986, connectionID).then(($result: any) => {
        return $$createType21($result);
    });
}

export function PickExportSavePath(ext: string): $CancellablePromise<string> {
    return $Call.ByID(1154457340, ext);
}

export function PickSQLiteFile(): $CancellablePromise<string> {
    return $Call.ByID(2769801138);
}

export function QueryTable(connectionID: string, req: database$0.TableDataRequest): $CancellablePromise<database$0.QueryResult | null> {
    return $Call.ByID(3137754197, connectionID, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function QueryTableStream(connectionID: string, tabID: string, req: database$0.TableDataRequest): $CancellablePromise<void> {
    return $Call.ByID(3607474293, connectionID, tabID, req);
}

export function ReorderConnections(orderedIDs: string[]): $CancellablePromise<boolean> {
    return $Call.ByID(2307732985, orderedIDs);
}

/**
 * RollbackTransaction rolls back the open transaction on the tab and releases the pinned connection.
 */
export function RollbackTransaction(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(546324027, tabID);
}

export function SaveConnection(cfg: database$0.ConnectionConfig): $CancellablePromise<database$0.ConnectionConfig> {
    return $Call.ByID(571429232, cfg).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SaveEditorSession(session: storage$0.EditorSession): $CancellablePromise<void> {
    return $Call.ByID(3313325587, session);
}

export function SaveFolder(f: storage$0.ConnectionFolder): $CancellablePromise<storage$0.ConnectionFolder> {
    return $Call.ByID(1026390748, f).then(($result: any) => {
        return $$createType13($result);
    });
}

export function SaveSavedQuery(q: database$0.SavedQuery): $CancellablePromise<database$0.SavedQuery> {
    return $Call.ByID(1936361457, q).then(($result: any) => {
        return $$createType15($result);
    });
}

export function SaveTextFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3576490577, path, content);
}

export function SetPendingFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(2899318644, path);
}

/**
 * SetSetting persists one preference; keys (e.g. "xensql-theme") are opaque here.
 */
export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2719370137, key, value);
}

export function SetWindowStateFlush(flush: any): $CancellablePromise<void> {
    return $Call.ByID(844868674, flush);
}

export function SettingsStore(): $CancellablePromise<storage$0.SettingsStore | null> {
    return $Call.ByID(2329735545).then(($result: any) => {
        return $$createType23($result);
    });
}

export function SupportedDrivers(): $CancellablePromise<string[]> {
    return $Call.ByID(4071936312).then(($result: any) => {
        return $$createType24($result);
    });
}

export function TestConnection(cfg: database$0.ConnectionConfig): $CancellablePromise<void> {
    return $Call.ByID(1803584041, cfg);
}

/**
 * TransactionStatus returns whether the given tab has an active transaction.
 */
export function TransactionStatus(tabID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3593372869, tabID);
}

export function UpdateRow(connectionID: string, upd: database$0.RowUpdate): $CancellablePromise<void> {
    return $Call.ByID(1118365152, connectionID, upd);
}

// Private type creation functions
const $$createType0 = database$0.QueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.AppInfo.createFrom;
const $$createType3 = database$0.ConnectionStatus.createFrom;
const $$createType4 = storage$0.EditorSession.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = database$0.HistoryEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = database$0.ColumnInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = database$0.ConnectionConfig.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = storage$0.ConnectionFolder.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = database$0.SavedQuery.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = database$0.SchemaInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = database$0.TableInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = database$0.SchemaBundle.createFrom;
const $$createType22 = storage$0.SettingsStore.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $Create.Array($Create.Any);
