// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConnectionFolder {
    "id": string;
    "name": string;

    /** Creates a new ConnectionFolder instance. */
    constructor($$source: Partial<ConnectionFolder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionFolder instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionFolder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionFolder($$parsedSource as Partial<ConnectionFolder>);
    }
}

export class EditorSession {
    "tabs": EditorTab[];
    "activeTab": string;

    /** Creates a new EditorSession instance. */
    constructor($$source: Partial<EditorSession> = {}) {
        if (!("tabs" in $$source)) {
            this["tabs"] = [];
        }
        if (!("activeTab" in $$source)) {
            this["activeTab"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorSession instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorSession {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField0_0($$parsedSource["tabs"]);
        }
        return new EditorSession($$parsedSource as Partial<EditorSession>);
    }
}

export class EditorTab {
    "id": string;
    "connectionId": string;
    "title": string;
    "sql": string;
    "color": string;
    "savedQueryId"?: string;
    "savedSqlBaseline"?: string;
    "tableView"?: TableViewRef | null;

    /** Creates a new EditorTab instance. */
    constructor($$source: Partial<EditorTab> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorTab instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorTab {
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tableView" in $$parsedSource) {
            $$parsedSource["tableView"] = $$createField7_0($$parsedSource["tableView"]);
        }
        return new EditorTab($$parsedSource as Partial<EditorTab>);
    }
}

/**
 * SettingsStore is a flat key/value store persisted as settings.json, holding the
 * frontend's preferences in the portable data dir (not the WebView's localStorage).
 */
export class SettingsStore {

    /** Creates a new SettingsStore instance. */
    constructor($$source: Partial<SettingsStore> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsStore instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsStore {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsStore($$parsedSource as Partial<SettingsStore>);
    }
}

export class TableViewRef {
    "schema": string;
    "table": string;
    "filter"?: string;
    "orderBy"?: string;
    "orderDir"?: string;

    /** Creates a new TableViewRef instance. */
    constructor($$source: Partial<TableViewRef> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableViewRef instance from a string or object.
     */
    static createFrom($$source: any = {}): TableViewRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableViewRef($$parsedSource as Partial<TableViewRef>);
    }
}

// Private type creation functions
const $$createType0 = EditorTab.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = TableViewRef.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
