// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginTransaction(arg1, arg2) {
  return window['go']['app']['App']['BeginTransaction'](arg1, arg2);
}

export function CancelQuery(arg1) {
  return window['go']['app']['App']['CancelQuery'](arg1);
}

export function CleanupTabTransaction(arg1) {
  return window['go']['app']['App']['CleanupTabTransaction'](arg1);
}

export function ClearQueryHistory(arg1) {
  return window['go']['app']['App']['ClearQueryHistory'](arg1);
}

export function CommitTransaction(arg1) {
  return window['go']['app']['App']['CommitTransaction'](arg1);
}

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['app']['App']['CopyToClipboard'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['app']['App']['DeleteFolder'](arg1);
}

export function DeleteQueryHistoryEntry(arg1) {
  return window['go']['app']['App']['DeleteQueryHistoryEntry'](arg1);
}

export function DeleteRows(arg1, arg2) {
  return window['go']['app']['App']['DeleteRows'](arg1, arg2);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['app']['App']['DeleteSavedQuery'](arg1);
}

export function DeleteSetting(arg1) {
  return window['go']['app']['App']['DeleteSetting'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['app']['App']['Disconnect'](arg1);
}

export function EmitOpenSQLite(arg1) {
  return window['go']['app']['App']['EmitOpenSQLite'](arg1);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['app']['App']['ExecuteQuery'](arg1, arg2);
}

export function ExecuteQueryStream(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteQueryStream'](arg1, arg2, arg3);
}

export function ExportResult(arg1, arg2) {
  return window['go']['app']['App']['ExportResult'](arg1, arg2);
}

export function FormatSQL(arg1) {
  return window['go']['app']['App']['FormatSQL'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetConnectionStatus(arg1) {
  return window['go']['app']['App']['GetConnectionStatus'](arg1);
}

export function GetDataDir() {
  return window['go']['app']['App']['GetDataDir']();
}

export function GetEditorSession() {
  return window['go']['app']['App']['GetEditorSession']();
}

export function GetPendingFile() {
  return window['go']['app']['App']['GetPendingFile']();
}

export function GetQueryHistory(arg1, arg2) {
  return window['go']['app']['App']['GetQueryHistory'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function InsertRow(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['InsertRow'](arg1, arg2, arg3, arg4);
}

export function IsConnected(arg1) {
  return window['go']['app']['App']['IsConnected'](arg1);
}

export function ListColumns(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListColumns'](arg1, arg2, arg3);
}

export function ListConnections() {
  return window['go']['app']['App']['ListConnections']();
}

export function ListFolders() {
  return window['go']['app']['App']['ListFolders']();
}

export function ListSavedQueries(arg1) {
  return window['go']['app']['App']['ListSavedQueries'](arg1);
}

export function ListSchemas(arg1) {
  return window['go']['app']['App']['ListSchemas'](arg1);
}

export function ListTables(arg1, arg2) {
  return window['go']['app']['App']['ListTables'](arg1, arg2);
}

export function LoadSchemaData(arg1) {
  return window['go']['app']['App']['LoadSchemaData'](arg1);
}

export function PickExportSavePath(arg1) {
  return window['go']['app']['App']['PickExportSavePath'](arg1);
}

export function PickSQLiteFile() {
  return window['go']['app']['App']['PickSQLiteFile']();
}

export function QueryTable(arg1, arg2) {
  return window['go']['app']['App']['QueryTable'](arg1, arg2);
}

export function QueryTableStream(arg1, arg2, arg3) {
  return window['go']['app']['App']['QueryTableStream'](arg1, arg2, arg3);
}

export function ReorderConnections(arg1) {
  return window['go']['app']['App']['ReorderConnections'](arg1);
}

export function RollbackTransaction(arg1) {
  return window['go']['app']['App']['RollbackTransaction'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['app']['App']['SaveConnection'](arg1);
}

export function SaveEditorSession(arg1) {
  return window['go']['app']['App']['SaveEditorSession'](arg1);
}

export function SaveFolder(arg1) {
  return window['go']['app']['App']['SaveFolder'](arg1);
}

export function SaveSavedQuery(arg1) {
  return window['go']['app']['App']['SaveSavedQuery'](arg1);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['app']['App']['SaveTextFile'](arg1, arg2);
}

export function SetPendingFile(arg1) {
  return window['go']['app']['App']['SetPendingFile'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['app']['App']['SetSetting'](arg1, arg2);
}

export function SupportedDrivers() {
  return window['go']['app']['App']['SupportedDrivers']();
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function TransactionStatus(arg1) {
  return window['go']['app']['App']['TransactionStatus'](arg1);
}

export function UpdateRow(arg1, arg2) {
  return window['go']['app']['App']['UpdateRow'](arg1, arg2);
}
