// Command bump-version updates app version in files that are not regenerated by
// `wails3 task common:update:build-assets`, then always runs that task so build/
// metadata stays in sync with build/config.yml.
//
// Usage:
//
//	go run ./scripts/bump-version.go -minor
//	go run ./scripts/bump-version.go -patch
//	go run ./scripts/bump-version.go -major
//	go run ./scripts/bump-version.go 1.2.0
//	go run ./scripts/bump-version.go -dry-run -minor
//	go run ./scripts/bump-version.go -sync
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

const versionGoRel = `internal/app/version.go`

var (
	flagMajor  = flag.Bool("major", false, "bump major version (1.1.2 -> 2.0.0)")
	flagMinor  = flag.Bool("minor", false, "bump minor version (1.1.2 -> 1.2.0)")
	flagPatch  = flag.Bool("patch", false, "bump patch version (1.1.2 -> 1.1.3)")
	flagDryRun = flag.Bool("dry-run", false, "print planned changes without writing files")
	flagSync   = flag.Bool("sync", false, "sync non-build files to internal/app/version.go without bumping")
)

func main() {
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: go run ./scripts/bump-version.go [flags] [version]\n\n")
		fmt.Fprintf(os.Stderr, "Updates version.go, build/config.yml, and frontend metadata, then runs\n")
		fmt.Fprintf(os.Stderr, "wails3 task common:update:build-assets to refresh everything under build/.\n\n")
		fmt.Fprintf(os.Stderr, "Examples:\n")
		fmt.Fprintf(os.Stderr, "  go run ./scripts/bump-version.go -minor\n")
		fmt.Fprintf(os.Stderr, "  go run ./scripts/bump-version.go -patch\n")
		fmt.Fprintf(os.Stderr, "  go run ./scripts/bump-version.go 1.2.0\n")
		fmt.Fprintf(os.Stderr, "  go run ./scripts/bump-version.go -dry-run -minor\n")
		fmt.Fprintf(os.Stderr, "  go run ./scripts/bump-version.go -sync\n\n")
		flag.PrintDefaults()
	}
	flag.Parse()

	root, err := findRepoRoot()
	if err != nil {
		fatal("%v", err)
	}

	current, err := readCurrentVersion(filepath.Join(root, versionGoRel))
	if err != nil {
		fatal("%v", err)
	}

	if *flagSync && (flag.NArg() > 0 || *flagMajor || *flagMinor || *flagPatch) {
		fatal("use -sync alone, without bump flags or an explicit version")
	}

	target, err := resolveTargetVersion(current, flag.Args())
	if err != nil {
		fatal("%v", err)
	}

	if *flagSync {
		fmt.Printf("Syncing non-build version files to %s\n", current)
	} else if target == current {
		fmt.Printf("Version is already %s; refreshing build assets\n", current)
	} else {
		fmt.Printf("Bumping version: %s -> %s\n", current, target)
	}

	updates := manualUpdates(target, *flagSync)
	if err := applyTextUpdates(root, updates, *flagDryRun); err != nil {
		fatal("%v", err)
	}
	if err := updatePackageLock(root, target, *flagDryRun); err != nil {
		fatal("%v", err)
	}

	if *flagDryRun {
		fmt.Println("  would run wails3 task common:update:build-assets")
		fmt.Println("Dry run complete; no files were modified.")
		return
	}

	if err := refreshBuildAssets(root); err != nil {
		fatal("%v", err)
	}

	fmt.Println("Version bump complete.")
	fmt.Printf("Next: commit, then tag and push (e.g. git tag v%s && git push origin v%s)\n", target, target)
}

func manualUpdates(target string, sync bool) []fileUpdate {
	updates := []fileUpdate{
		{
			path:    "build/config.yml",
			replace: regexp.MustCompile(`(?m)^  version: "[^"]+" # The application version\s*$`),
			with:    fmt.Sprintf(`  version: "%s" # The application version`, target),
		},
		{
			path:    "frontend/package.json",
			replace: regexp.MustCompile(`"version": "[^"]+"`),
			with:    fmt.Sprintf(`"version": "%s"`, target),
		},
		{
			path:    "frontend/src/shared/lib/appInfo.ts",
			replace: regexp.MustCompile(`version: '[^']+'`),
			with:    fmt.Sprintf(`version: '%s'`, target),
		},
	}
	if !sync {
		updates = append([]fileUpdate{{
			path:    "internal/app/version.go",
			replace: regexp.MustCompile(`const Version = "[^"]+"`),
			with:    fmt.Sprintf(`const Version = "%s"`, target),
		}}, updates...)
	}
	return updates
}

type fileUpdate struct {
	path    string
	replace *regexp.Regexp
	with    string
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repo root (no go.mod in parents of %s)", dir)
		}
		dir = parent
	}
}

func readCurrentVersion(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	re := regexp.MustCompile(`const Version = "([^"]+)"`)
	m := re.FindSubmatch(data)
	if len(m) != 2 {
		return "", fmt.Errorf("could not parse version from %s", path)
	}
	return string(m[1]), nil
}

func resolveTargetVersion(current string, args []string) (string, error) {
	bumpCount := 0
	if *flagMajor {
		bumpCount++
	}
	if *flagMinor {
		bumpCount++
	}
	if *flagPatch {
		bumpCount++
	}

	switch {
	case len(args) > 1:
		return "", fmt.Errorf("expected at most one explicit version argument, got %q", strings.Join(args, " "))
	case len(args) == 1:
		if bumpCount > 0 {
			return "", fmt.Errorf("use either bump flags (-major/-minor/-patch) or an explicit version, not both")
		}
		return normalizeVersion(args[0])
	case bumpCount == 0:
		if *flagSync {
			return normalizeVersion(current)
		}
		return "", fmt.Errorf("specify -major, -minor, -patch, -sync, or an explicit version (e.g. 1.2.0)")
	case bumpCount > 1:
		return "", fmt.Errorf("use only one of -major, -minor, or -patch")
	case *flagMajor:
		return bumpSemver(current, major)
	case *flagMinor:
		return bumpSemver(current, minor)
	default:
		return bumpSemver(current, patch)
	}
}

type bumpKind int

const (
	major bumpKind = iota
	minor
	patch
)

func bumpSemver(v string, kind bumpKind) (string, error) {
	v, err := normalizeVersion(v)
	if err != nil {
		return "", err
	}
	parts := strings.Split(v, ".")
	if len(parts) != 3 {
		return "", fmt.Errorf("unsupported version format %q (expected X.Y.Z)", v)
	}
	nums := make([]int, 3)
	for i, part := range parts {
		n, err := strconv.Atoi(part)
		if err != nil {
			return "", fmt.Errorf("invalid version segment %q in %q", part, v)
		}
		nums[i] = n
	}

	switch kind {
	case major:
		return fmt.Sprintf("%d.0.0", nums[0]+1), nil
	case minor:
		return fmt.Sprintf("%d.%d.0", nums[0], nums[1]+1), nil
	default:
		return fmt.Sprintf("%d.%d.%d", nums[0], nums[1], nums[2]+1), nil
	}
}

func normalizeVersion(v string) (string, error) {
	v = strings.TrimSpace(v)
	v = strings.TrimPrefix(v, "v")
	if !regexp.MustCompile(`^\d+\.\d+\.\d+$`).MatchString(v) {
		return "", fmt.Errorf("invalid version %q (expected X.Y.Z or vX.Y.Z)", v)
	}
	return v, nil
}

func applyTextUpdates(root string, updates []fileUpdate, dryRun bool) error {
	grouped := make(map[string][]fileUpdate)
	order := make([]string, 0, len(updates))
	for _, upd := range updates {
		if _, seen := grouped[upd.path]; !seen {
			order = append(order, upd.path)
		}
		grouped[upd.path] = append(grouped[upd.path], upd)
	}

	for _, rel := range order {
		path := filepath.Join(root, rel)
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", rel, err)
		}

		changed := false
		for _, upd := range grouped[rel] {
			if !upd.replace.Match(data) {
				return fmt.Errorf("version marker not found in %s", rel)
			}
			next := upd.replace.ReplaceAll(data, []byte(upd.with))
			if string(next) != string(data) {
				changed = true
			}
			data = next
		}

		if !changed {
			continue
		}

		if dryRun {
			fmt.Printf("  would update %s\n", rel)
			continue
		}
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", rel, err)
		}
		fmt.Printf("  updated %s\n", rel)
	}
	return nil
}

func replaceFirst(data []byte, re *regexp.Regexp, with string) ([]byte, bool) {
	loc := re.FindIndex(data)
	if loc == nil {
		return data, false
	}
	out := make([]byte, 0, len(data)-(loc[1]-loc[0])+len(with))
	out = append(out, data[:loc[0]]...)
	out = append(out, with...)
	out = append(out, data[loc[1]:]...)
	return out, true
}

func updatePackageLock(root, target string, dryRun bool) error {
	path := filepath.Join(root, "frontend/package-lock.json")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("read frontend/package-lock.json: %w", err)
	}

	reRoot := regexp.MustCompile(`(?m)^  "version": "[^"]+",\s*$`)
	rePkg := regexp.MustCompile(`(?m)^      "version": "[^"]+",\s*$`)

	next := data
	var changed bool
	next, ok := replaceFirst(next, reRoot, fmt.Sprintf(`  "version": "%s",`, target))
	changed = changed || ok
	next, ok = replaceFirst(next, rePkg, fmt.Sprintf(`      "version": "%s",`, target))
	changed = changed || ok

	if !changed {
		return nil
	}

	if dryRun {
		fmt.Printf("  would update frontend/package-lock.json\n")
		return nil
	}
	if err := os.WriteFile(path, next, 0o644); err != nil {
		return fmt.Errorf("write frontend/package-lock.json: %w", err)
	}
	fmt.Printf("  updated frontend/package-lock.json\n")
	return nil
}

func refreshBuildAssets(root string) error {
	fmt.Println("Refreshing build assets...")
	cmd := exec.Command("wails3", "task", "common:update:build-assets")
	cmd.Dir = root
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("wails3 task common:update:build-assets: %w", err)
	}
	return nil
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "error: "+format+"\n", args...)
	os.Exit(1)
}
