import type { ColumnInfo, DriverType } from '@/types';

export type InsertRowFieldMode = 'default' | 'null' | 'value';

export interface InsertRowFieldState {
  mode: InsertRowFieldMode;
  value: string;
}

export function isAutoGeneratedColumn(col: ColumnInfo, driver: DriverType): boolean {
  if (!col.defaultVal) {
    // serial/identity short-hands imply a sequence default even when the DB doesn't surface one.
    if (col.isPrimary && /^(?:serial|bigserial|smallserial)/i.test(col.dataType)) {
      return true;
    }
    // SQLite's INTEGER PRIMARY KEY is an auto-assigned rowid alias; on PG/MySQL an integer PK is only
    // auto when it has a sequence/AUTO_INCREMENT default (caught above), so this rule is SQLite-only.
    if (driver === 'sqlite' && col.isPrimary && /^integer$/i.test(col.dataType)) {
      return true;
    }
    return false;
  }
  const d = col.defaultVal.toLowerCase();
  return (
    d.includes('nextval(') ||
    d.includes('autoincrement') ||
    d.includes('auto_increment') ||
    d.includes('generated always') ||
    d.includes('generated by default')
  );
}

export function isInsertInputHidden(col: ColumnInfo, driver: DriverType): boolean {
  return isAutoGeneratedColumn(col, driver);
}

export function requiresInsertValue(col: ColumnInfo, driver: DriverType): boolean {
  return !isInsertInputHidden(col, driver) && !col.isNullable && !hasDbDefault(col, driver);
}

export function hasDbDefault(col: ColumnInfo, driver: DriverType): boolean {
  return isAutoGeneratedColumn(col, driver) || !!col.defaultVal?.trim();
}

export function canUseDefaultMode(col: ColumnInfo, driver: DriverType): boolean {
  if (isAutoGeneratedColumn(col, driver)) return true;
  if (col.defaultVal?.trim()) return true;
  return col.isNullable;
}

export function canUseNullMode(col: ColumnInfo): boolean {
  return col.isNullable;
}

export function initialFieldMode(col: ColumnInfo, driver: DriverType): InsertRowFieldMode {
  if (isAutoGeneratedColumn(col, driver) || col.defaultVal?.trim()) return 'default';
  if (!col.isNullable) return 'value';
  return 'default';
}

export function createInitialFieldStates(
  columns: ColumnInfo[],
  driver: DriverType
): Record<string, InsertRowFieldState> {
  const states: Record<string, InsertRowFieldState> = {};
  for (const col of columns) {
    states[col.name] = { mode: initialFieldMode(col, driver), value: '' };
  }
  return states;
}

export function formatDefaultHint(col: ColumnInfo, driver: DriverType, maxLen = 72): string {
  if (isAutoGeneratedColumn(col, driver)) return col.defaultVal?.trim() || col.dataType;
  const d = col.defaultVal?.trim() ?? '';
  if (!d) return '';
  return d.length > maxLen ? `${d.slice(0, maxLen)}…` : d;
}

export type InsertRowValidationCode =
  | 'required'
  | 'notNullable'
  | 'emptyInsert'
  | null;

export function validateInsertRowFields(
  columns: ColumnInfo[],
  states: Record<string, InsertRowFieldState>,
  driver: DriverType
): InsertRowValidationCode {
  let included = 0;
  for (const col of columns) {
    const s = states[col.name];
    if (!s) continue;

    if (isInsertInputHidden(col, driver)) continue;

    if (s.mode === 'default') {
      if (!canUseDefaultMode(col, driver)) return 'required';
      if (requiresInsertValue(col, driver)) return 'required';
      continue;
    }

    included++;
    if (s.mode === 'null') {
      if (!col.isNullable) return 'notNullable';
      continue;
    }

    if (s.value.trim() === '' && requiresInsertValue(col, driver)) {
      return 'required';
    }
  }
  if (included === 0) return 'emptyInsert';
  return null;
}

export function buildInsertRowPayload(
  columns: ColumnInfo[],
  states: Record<string, InsertRowFieldState>,
  driver: DriverType
): Record<string, unknown> {
  const values: Record<string, unknown> = {};
  for (const col of columns) {
    const s = states[col.name];
    if (!s || isInsertInputHidden(col, driver) || s.mode === 'default') continue;
    values[col.name] = s.mode === 'null' ? null : s.value;
  }
  return values;
}
