import { describe, expect, it } from 'vitest';
import {
  buildInsertRowPayload,
  createInitialFieldStates,
  initialFieldMode,
  isAutoGeneratedColumn,
  isInsertInputHidden,
  requiresInsertValue,
  validateInsertRowFields,
} from '@/features/table-view/lib/insertRowForm';
import type { ColumnInfo } from '@/types';

const cols: ColumnInfo[] = [
  {
    name: 'id',
    dataType: 'integer',
    isNullable: false,
    isPrimary: true,
    defaultVal: "nextval('id_seq'::regclass)",
  },
  { name: 'email', dataType: 'varchar', isNullable: false, isPrimary: false },
  { name: 'note', dataType: 'text', isNullable: true, isPrimary: false },
];

describe('insertRowForm', () => {
  it('detects auto-generated columns', () => {
    expect(isAutoGeneratedColumn(cols[0], 'postgres')).toBe(true);
    expect(isAutoGeneratedColumn(cols[1], 'postgres')).toBe(false);
  });

  it('treats a bare integer PK as auto-generated only on SQLite (rowid alias)', () => {
    const intPk: ColumnInfo = {
      name: 'id',
      dataType: 'integer',
      isNullable: false,
      isPrimary: true,
    };
    expect(isAutoGeneratedColumn(intPk, 'sqlite')).toBe(true);
    // On Postgres/MySQL a plain integer PK is user-supplied unless a sequence/auto_increment default exists.
    expect(isAutoGeneratedColumn(intPk, 'postgres')).toBe(false);
    expect(isAutoGeneratedColumn(intPk, 'mysql')).toBe(false);
    expect(isInsertInputHidden(intPk, 'postgres')).toBe(false);
    expect(requiresInsertValue(intPk, 'postgres')).toBe(true);
  });

  it('detects MySQL auto_increment via the default', () => {
    const autoInc: ColumnInfo = {
      name: 'id',
      dataType: 'int',
      isNullable: false,
      isPrimary: true,
      defaultVal: 'auto_increment',
    };
    expect(isAutoGeneratedColumn(autoInc, 'mysql')).toBe(true);
  });

  it('pre-selects default mode when column has a default', () => {
    expect(initialFieldMode(cols[0], 'postgres')).toBe('default');
    expect(initialFieldMode(cols[1], 'postgres')).toBe('value');
    expect(initialFieldMode(cols[2], 'postgres')).toBe('default');
  });

  it('rejects empty insert payload', () => {
    const nullableOnly: ColumnInfo[] = [
      { name: 'a', dataType: 'text', isNullable: true, isPrimary: false },
      { name: 'b', dataType: 'text', isNullable: true, isPrimary: false },
    ];
    const states = createInitialFieldStates(nullableOnly, 'postgres');
    expect(validateInsertRowFields(nullableOnly, states, 'postgres')).toBe('emptyInsert');
  });

  it('nullable FK-like columns are not required', () => {
    const fk: ColumnInfo = {
      name: 'user_id',
      dataType: 'integer',
      isNullable: true,
      isPrimary: false,
    };
    expect(requiresInsertValue(fk, 'postgres')).toBe(false);
    expect(isInsertInputHidden(fk, 'postgres')).toBe(false);
  });

  it('builds payload for null and value modes', () => {
    const states = createInitialFieldStates(cols, 'postgres');
    states.email = { mode: 'value', value: 'a@b.c' };
    states.note = { mode: 'null', value: '' };
    expect(validateInsertRowFields(cols, states, 'postgres')).toBe(null);
    expect(buildInsertRowPayload(cols, states, 'postgres')).toEqual({
      email: 'a@b.c',
      note: null,
    });
  });
});
