// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';
import {storage} from '../models';

export function BeginTransaction(arg1:string,arg2:string):Promise<void>;

export function CancelQuery(arg1:string):Promise<boolean>;

export function CleanupTabTransaction(arg1:string):Promise<void>;

export function ClearQueryHistory(arg1:string):Promise<void>;

export function CommitTransaction(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<boolean>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteQueryHistoryEntry(arg1:string):Promise<boolean>;

export function DeleteRows(arg1:string,arg2:database.RowDelete):Promise<number>;

export function DeleteSavedQuery(arg1:string):Promise<boolean>;

export function DeleteSetting(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<database.QueryResult>;

export function ExecuteQueryStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportResult(arg1:database.QueryResult,arg2:string):Promise<string>;

export function FormatSQL(arg1:string):Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetConnectionStatus(arg1:string):Promise<database.ConnectionStatus>;

export function GetDataDir():Promise<string>;

export function GetEditorSession():Promise<storage.EditorSession>;

export function GetPendingFile():Promise<Record<string, string>>;

export function GetQueryHistory(arg1:string,arg2:number):Promise<Array<database.HistoryEntry>>;

export function GetSettings():Promise<Record<string, string>>;

export function InsertRow(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<Record<string, any>>;

export function IsConnected(arg1:string):Promise<boolean>;

export function ListColumns(arg1:string,arg2:string,arg3:string):Promise<Array<database.ColumnInfo>>;

export function ListConnections():Promise<Array<database.ConnectionConfig>>;

export function ListFolders():Promise<Array<storage.ConnectionFolder>>;

export function ListSavedQueries(arg1:string):Promise<Array<database.SavedQuery>>;

export function ListSchemas(arg1:string):Promise<Array<database.SchemaInfo>>;

export function ListTables(arg1:string,arg2:string):Promise<Array<database.TableInfo>>;

export function LoadSchemaData(arg1:string):Promise<database.SchemaBundle>;

export function PickExportSavePath(arg1:string):Promise<string>;

export function PickSQLiteFile():Promise<string>;

export function QueryTable(arg1:string,arg2:database.TableDataRequest):Promise<database.QueryResult>;

export function QueryTableStream(arg1:string,arg2:string,arg3:database.TableDataRequest):Promise<void>;

export function ReorderConnections(arg1:Array<string>):Promise<boolean>;

export function RollbackTransaction(arg1:string):Promise<void>;

export function SaveConnection(arg1:database.ConnectionConfig):Promise<database.ConnectionConfig>;

export function SaveEditorSession(arg1:storage.EditorSession):Promise<void>;

export function SaveFolder(arg1:storage.ConnectionFolder):Promise<storage.ConnectionFolder>;

export function SaveSavedQuery(arg1:database.SavedQuery):Promise<database.SavedQuery>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SupportedDrivers():Promise<Array<string>>;

export function TestConnection(arg1:database.ConnectionConfig):Promise<void>;

export function TransactionStatus(arg1:string):Promise<boolean>;

export function UpdateRow(arg1:string,arg2:database.RowUpdate):Promise<void>;
